CREATE DATABASE Group03;
GO

USE Group03;
GO

CREATE TABLE Departments (
	Dnum INT PRIMARY KEY IDENTITY(1, 1),
	Dname NVARCHAR(20) NOT NULL,
	Manager_SSN INT NOT NULL,
	FOREIGN KEY (Manager_SSN) REFERENCES Employees(SSN)
);
GO

CREATE TABLE Department_Locations (
	Dnum INT NOT NULL,
	Location NVARCHAR(50) NOT NULL,
	FOREIGN KEY (Dnum) REFERENCES Departments(Dnum),
	PRIMARY KEY (Dnum, Location)
);
GO

CREATE TABLE Projects (
	PNum INT PRIMARY KEY IDENTITY(1, 1),
	Location NVARCHAR(50) NOT NULL,
	PName NVARCHAR(40) NOT NULL,
	City NVARCHAR(30) NOT NULL,
	Dnum INT NOT NULL FOREIGN KEY (Dnum) REFERENCES Departments(Dnum)
);
GO

CREATE TABLE Employees (
	SSN INT PRIMARY KEY IDENTITY(1, 1),
	FName NVARCHAR(20) NOT NULL,
	LName NVARCHAR(20) NOT NULL,
	BirthDate DATE NOT NULL,
	Super_SSN INT NOT NULL,
	Salary MONEY NOT NULL,
	DNUM INT NOT NULL,
	FOREIGN KEY (Super_SSN) REFERENCES Employees (SSN),
	--FOREIGN KEY (DNUM) REFERENCES Departments (Dnum)
);
GO

CREATE TABLE Employee_Projects (
	ESSN INT NOT NULL,
	PNum INT NOT NULL,
	NumOfHours INT NOT NULL,
	FOREIGN KEY (ESSN) REFERENCES Employees (SSN),
	FOREIGN KEY (PNum) REFERENCES Projects (PNum)
);
GO

CREATE TABLE Dependents (
	Name NVARCHAR(30) NOT NULL,
	BirthDate DATE NOT NULL,
	Gender NVARCHAR(20) NOT NULL,
	ESSN INT NOT NULL,
	FOREIGN KEY (ESSN) REFERENCES Employees (SSN),
	PRIMARY KEY (ESSN, Name)
);

ALTER TABLE Employees
 ADD CONSTRAINT FK_DNUM_Employees FOREIGN KEY (DNUM) REFERENCES Departments (Dnum)